
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9094
  redis:
    host: redis
    port: 6379
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1.0
